" Load default onfiguration
if filereadable("/etc/vimrc")
	source /etc/vimrc
endif
if filereadable("/usr/share/vim/vim80/defaults.vim")
	source /usr/share/vim/vim80/defaults.vim
endif

colorscheme desert
"if &diff
"endif

" Tab switch
nnoremap tj :tabnext<cr>
nnoremap tk :tabprev<cr>
